session_type: "llm"
model_id: "unsloth/mistral-7b-instruct-v0.3-bnb-4bit"
tokenizer_id: "mistralai/Mistral-7B-Instruct-v0.3"

embedding_model_id: "sentence-transformers/all-MiniLM-L6-v2"
embedding_tokenizer_id: "sentence-transformers/all-MiniLM-L6-v2"

memories_dir: "/content/drive/MyDrive/llm_memories"

batch_size: 16
variance_scaling_factor: 0.6
threshold: "None"

k_memmories: 10
k_top_k_memmories: 6 

gradio_config:
  height: 400 
  textbox_placeholder: "want to talk with you about my day"
  textbox_container: false 
  textbox_scale: 7
  title: " ... "  
  description: "Can talk here about everything" 
  theme: "ocean" 
  cache_examples: true 

share_gradio: true

